// ============================================================================
// Demo seed. Replaces itself with your real DB once the PHP/MySQL API is wired.
// Dates are computed relative to "today" so the demo never goes stale.
// ============================================================================
const D = (n) => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); };

export const SEED = {
  meta: { version: 1, seeded: true },
  audit: [],

  users: [
    { id: "u-001", name: "Ahmad Raza",   username: "admin",   pass: "admin123", role: "Admin",      branch: "Head Office", phone: "+92 300 1112233", email: "ahmad@eduflow.pk", active: true },
    { id: "u-002", name: "Sana Mehmood", username: "sana",    pass: "sana123",  role: "Counselor",  branch: "Head Office", phone: "+92 321 4455667", email: "sana@eduflow.pk",  active: true },
    { id: "u-003", name: "Bilal Khan",   username: "bilal",   pass: "bilal123", role: "Counselor",  branch: "Clifton",     phone: "+92 333 7788990", email: "bilal@eduflow.pk", active: true },
    { id: "u-004", name: "Hira Qureshi", username: "hira",    pass: "hira123",  role: "Doc Processor", branch: "Head Office", phone: "+92 345 2233445", email: "hira@eduflow.pk", active: true },
    { id: "u-005", name: "Usman Tariq",  username: "usman",   pass: "usman123", role: "Accounts",   branch: "Head Office", phone: "+92 302 6677889", email: "usman@eduflow.pk", active: true },
  ],

  universities: [
    { id: "uni-001", name: "University of Greenwich", country: "UK", city: "London", ranking: "101-150", min_ielts: "6.5 (6.0)", min_pct: 60, intake: ["Sep-26", "Jan-27"], deadline: D(64), tuition: 17500, currency: "GBP", scholar: "Vice-Chancellor's Intl £3,000", agent_comm_pct: 15, level: "Both", notes: "Accepts clearing for Sep intake. Strong for Business/Computing." },
    { id: "uni-002", name: "Coventry University", country: "UK", city: "Coventry", ranking: "301-350", min_ielts: "6.0 (5.5)", min_pct: 55, intake: ["Sep-26", "Jan-27", "May-26"], deadline: D(31), tuition: 16420, currency: "GBP", scholar: "Global Business Excellence £4,000", agent_comm_pct: 15, level: "Both", notes: "Package interview model — very high approval from Pakistan. ATAS rarely needed except engineering." },
    { id: "uni-003", name: "University of West London", country: "UK", city: "London", ranking: "351-400", min_ielts: "6.0", min_pct: 55, intake: ["Sep-26", "Jan-27"], deadline: D(45), tuition: 15600, currency: "GBP", scholar: "Vice Chancellor £2,000", agent_comm_pct: 18, level: "Both", notes: "Nursing/Midwifery needs no IELTS for some routes — check current rule." },
    { id: "uni-004", name: "Dublin Business School", country: "IE", city: "Dublin", ranking: "—", min_ielts: "6.5 (6.0)", min_pct: 60, intake: ["Sep-26", "Jan-27"], deadline: D(90), tuition: 12500, currency: "EUR", scholar: "DBS merit €2,000", agent_comm_pct: 15, level: "Both", notes: "2-year stay-back post Master's. InIS exemption if scholarship >50%." },
    { id: "uni-005", name: "Technological University Dublin", country: "IE", city: "Dublin", ranking: "551-600", min_ielts: "6.5", min_pct: 60, intake: ["Sep-26"], deadline: D(60), tuition: 11200, currency: "EUR", scholar: "TUD Intl Grant €3,000", agent_comm_pct: 12, level: "Both", notes: "Requires 6-month bank history; stricter on source of funds than private colleges." },
    { id: "uni-006", name: "Istanbul Bilgi University", country: "TR", city: "Istanbul", ranking: "801-1000", min_ielts: "6.0", min_pct: 50, intake: ["Sep-26"], deadline: D(120), tuition: 5200, currency: "USD", scholar: "50% merit waiver", agent_comm_pct: 10, level: "Both", notes: "No IELTS if medium of instruction cert. Denklik needed before residence permit." },
    { id: "uni-007", name: "Yıldız Technical University", country: "TR", city: "Istanbul", ranking: "601-700", min_ielts: "6.5 / TÖMER C1", min_pct: 70, intake: ["Sep-26"], deadline: D(75), tuition: 2400, currency: "USD", scholar: "Türkiye Bursları (full)", agent_comm_pct: 0, level: "Both", notes: "State — apply via Turkiye Burslari scholarship window (Jan-Feb). No commission." },
    { id: "uni-008", name: "Taylor's University", country: "MY", city: "Subang Jaya", ranking: "291", min_ielts: "6.0", min_pct: 60, intake: ["Mar-26", "Aug-26"], deadline: D(52), tuition: 14800, currency: "MYR", scholar: "Taylor's Merit 30%", agent_comm_pct: 12, level: "Both", notes: "Hospitality #1 in SEA. EMGS must start 60 days before intake." },
    { id: "uni-009", name: "University of Malaya", country: "MY", city: "Kuala Lumpur", ranking: "65", min_ielts: "6.0", min_pct: 65, intake: ["Sep-26", "Feb-27"], deadline: D(105), tuition: 6900, currency: "MYR", scholar: "UM Global Scholarship", agent_comm_pct: 8, level: "Both", notes: "MTIB attestation on all transcripts. Long EMGS queue in Jun-Aug." },
    { id: "uni-010", name: "Asia Pacific University", country: "MY", city: "Kuala Lumpur", ranking: "601+", min_ielts: "5.5", min_pct: 50, intake: ["Feb-26", "Jul-26", "Oct-26"], deadline: D(28), tuition: 9500, currency: "MYR", scholar: "Apu Impact 25%", agent_comm_pct: 15, level: "Both", notes: "Three intakes = good for late/deferred students. CS & Data focus." },
  ],

  partners: [
    { id: "ag-001", name: "Oxford Bridge Education", type: "Sub-Agent", country: "PK", city: "Lahore", contact: "Faizan Aslam", phone: "+92 300 8471234", email: "faizan@oxfordbridge.pk", commission_pct: 20, contract_exp: D(210), ledger_bal: 145000, rating: "A", notes: "Sends 6-8 UK Master's files/month. Wants 100% release at visa approval." },
    { id: "ag-002", name: "Gulf Star Consultants", type: "Referral Partner", country: "AE", city: "Dubai", contact: "Rashid Mehmood", phone: "+971 50 7712233", email: "info@gulfstar.ae", commission_pct: 15, contract_exp: D(-25), ledger_bal: -40000, rating: "B", notes: "Malaysia + Türkiye mostly from Pakistani diaspora. Contract EXPIRED — renew." },
    { id: "ag-003", name: "Karachi IELTS Centre", type: "Test Center", country: "PK", city: "Karachi", contact: "Nadia Sheikh", phone: "+92 21 35871234", email: "booking@khielts.pk", commission_pct: 5, contract_exp: D(400), ledger_bal: 0, rating: "A", notes: "Batch discount for 10+ students; refer before test booking." },
    { id: "ag-004", name: "Iqbal & Associates (Attestation)", type: "Other", country: "PK", city: "Karachi", contact: "Adv. T. Iqbal", phone: "+92 321 9933111", email: "iqbal.att@ctg.net.pk", commission_pct: 0, contract_exp: D(160), ledger_bal: 22000, rating: "C", notes: "MOFA + embassy attestation. Turnaround slipping to 9 days — watch." },
    { id: "ag-005", name: "Ege Education Bureau", type: "University Rep", country: "TR", city: "Izmir", contact: "Merve Yilmaz", phone: "+90 532 1188223", email: "merve@egeedu.com.tr", commission_pct: 8, contract_exp: D(95), ledger_bal: 0, rating: "B", notes: "Bilateral for Türkiye private unis; handles our denklik follow-ups." },
  ],

  leads: [
    { id: "l-001", name: "Areeba Siddiqui", phone: "+92 336 2100111", email: "areeba.s@gmail.com", stage: "docs_ready", country: "UK", intake: "Sep-26", course_lvl: "Master", field_of_study: "Data Science", source: "Referral", status: "Hot", owner: "u-002", english_test: "IELTS UKVI", test_score: "7.0", test_date: D(-38), next_action_date: D(1), annual_income: 8500000, passport_no: "CC1234567", passport_exp: D(1500), city: "Karachi", tags: ["STEM", "ATAS?", "Sponsor: Father"], notes: "Father is bank manager — clean SOF. Needs ATAS check (Data Science with cyber module).", created: D(-24) },
    { id: "l-002", name: "Hamza Sheikh", phone: "+92 301 5566778", email: "hamza.sheikh@outlook.com", stage: "counselled", country: "IE", intake: "Sep-26", course_lvl: "Master", field_of_study: "Supply Chain", source: "Facebook", status: "Nurture", owner: "u-003", english_test: "PTE", test_score: "58", test_date: D(-15), next_action_date: D(-2), annual_income: 4200000, passport_no: "RW9988776", passport_exp: D(900), city: "Lahore", tags: ["Funds Gap"], notes: "Needs €10k living proof — only showing PKR 18 lakh. Advised 6-month accumulation.", created: D(-41) },
    { id: "l-003", name: "Zoya Ahmed", phone: "+92 345 9922110", email: "zoya.ahmed99@gmail.com", stage: "new", country: "TR", intake: "Sep-26", course_lvl: "Bachelor", field_of_study: "Interior Design", source: "Walk-in", status: "Open", owner: "u-002", english_test: "None", next_action_date: D(0), annual_income: 3000000, passport_no: "AB5566778", passport_exp: D(700), city: "Karachi", tags: ["Budget"], notes: "Family budget USD 4k/yr tuition. TÖMER route acceptable.", created: D(-1) },
    { id: "l-004", name: "Daniyal Riaz", phone: "+92 312 4477889", email: "daniyal.riaz@yahoo.com", stage: "contacted", country: "MY", intake: "Aug-26", course_lvl: "Bachelor", field_of_study: "Computer Science", source: "Instagram", status: "Open", owner: "u-003", english_test: "Duolingo", test_score: "105", test_date: D(-60), next_action_date: D(2), annual_income: 5400000, passport_no: "PD4433221", passport_exp: D(1100), city: "Islamabad", tags: ["APU"], notes: "Wants 3-intake flexibility. Duolingo accepted by APU — confirm current EMGS view.", created: D(-19) },
    { id: "l-005", name: "Mahnoor Baig", phone: "+92 333 7711224", email: "mahnoor.baig@gmail.com", stage: "counselled", country: "UK", intake: "Jan-27", course_lvl: "Master", field_of_study: "Public Health", source: "Agent", status: "Nurture", owner: "u-002", english_test: "IELTS", test_score: "6.5", test_date: D(-120), next_action_date: D(-21), annual_income: 6100000, passport_no: "NS2211009", passport_exp: D(1300), city: "Karachi", tags: ["Re-sit"], notes: "Last IELTS is >2 yrs by Jan intake. Re-sit booked.", created: D(-52) },
    { id: "l-006", name: "Umar Farooq", phone: "+92 300 3344556", email: "umar.farooq@company.pk", stage: "new", country: "IE", intake: "Jan-27", course_lvl: "Master", field_of_study: "Fintech", source: "Website", status: "Open", owner: "u-003", english_test: "IELTS", test_score: "7.0", test_date: D(-8), next_action_date: D(1), annual_income: 12000000, passport_no: "LK7788990", passport_exp: D(2100), city: "Karachi", tags: ["Strong Profile"], notes: "3 yrs banking experience, self-funded. Priority — close this week.", created: D(-2) },
    { id: "l-007", name: "Iqra Shahzad", phone: "+92 324 8899001", email: "iqra.shahzad@gmail.com", stage: "docs_ready", country: "TR", intake: "Sep-26", course_lvl: "Master", field_of_study: "Architecture", source: "Seminar", status: "Hot", owner: "u-002", english_test: "TOEFL", test_score: "92", test_date: D(-200), next_action_date: D(0), annual_income: 4800000, passport_no: "MN1122334", passport_exp: D(800), city: "Faisalabad", tags: ["Denklik"], notes: "Denklik file submitted — waiting 5th week.", created: D(-66) },
    { id: "l-008", name: "Talha Noor", phone: "+92 347 1100223", email: "talha.noor@proton.me", stage: "contacted", country: "MY", intake: "Feb-27", course_lvl: "Diploma", field_of_study: "Hospitality", source: "Referral", status: "Nurture", owner: "u-003", english_test: "None", next_action_date: D(-6), annual_income: 2600000, passport_no: "TR5566778", passport_exp: D(450), city: "Hyderabad", tags: ["Passport Renewal"], notes: "Passport expires in 15 months — Malaysia wants 18+. Renew first.", created: D(-30) },
    { id: "l-009", name: "Noor Fatima", phone: "+92 311 6677890", email: "noor.fatima@gmail.com", stage: "new", country: "UK", intake: "Sep-26", course_lvl: "Foundation", field_of_study: "Business", source: "Facebook", status: "Open", owner: "u-002", english_test: "IELTS UKVI", test_score: "5.5", test_date: D(-12), next_action_date: D(1), annual_income: 7300000, passport_no: "PL9900112", passport_exp: D(1600), city: "Karachi", tags: ["Clearing"], notes: "Inter results 52% — needs Coventry foundation.", created: D(-4) },
    { id: "l-010", name: "Ahmed Nawaz", phone: "+92 322 9988776", email: "ahmed.nawaz@gmail.com", stage: "lost", country: "UK", intake: "Sep-26", course_lvl: "Master", field_of_study: "Project Mgmt", source: "Walk-in", status: "Closed-Lost", owner: "u-003", english_test: "PTE", test_score: "50", test_date: D(-90), annual_income: 3900000, passport_no: "KF3344556", passport_exp: D(600), city: "Rawalpindi", tags: ["Lost to agent"], notes: "Went direct with a cheaper agent for the same university. Follow up for Sep-27.", created: D(-80) },
  ],

  applications: [
    { id: "ap-001", title: "UK-26-001 Greenwich / Areeba", lead: "l-001", university: "uni-001", course: "MSc Data Science & AI", country: "UK", intake: "Sep-26", stage: "docs_ready", owner: "u-002", application_fee: 0, tuition: 17500, currency: "GBP", priority: "High", agent: "ag-001", commission_pct: 15, notes: "Portal draft submitted, awaiting SOP final. ATAS pre-check pending.", created: D(-14) },
    { id: "ap-002", title: "IE-26-002 DBS / Hamza", lead: "l-002", university: "uni-004", course: "MSc Global Supply Chain", country: "IE", intake: "Sep-26", stage: "applied", owner: "u-003", app_portal_ref: "DBS-88213", application_fee: 100, currency: "EUR", tuition: 12500, priority: "Normal", notes: "Conditional offer expected 10 working days. Funds still short — do not push for LOA.", created: D(-27) },
    { id: "ap-003", title: "UK-26-003 Coventry / Mahnoor", lead: "l-005", university: "uni-002", course: "MSc Public Health", country: "UK", intake: "Jan-27", stage: "offer", owner: "u-002", app_portal_ref: "CV-441209", tuition: 16420, currency: "GBP", offer_date: D(-9), priority: "Normal", agent: "ag-001", commission_pct: 20, notes: "Unconditional with £4,000 scholarship. Deposit paid.", created: D(-45) },
    { id: "ap-004", title: "TR-26-004 Bilgi / Iqra", lead: "l-007", university: "uni-006", course: "MArch Architecture", country: "TR", intake: "Sep-26", stage: "coe", owner: "u-002", application_fee: 60, currency: "USD", tuition: 5200, cas_i20_date: D(-5), priority: "Urgent", notes: "Acceptance + ICAB letter in. Denklik still under review — this is the critical path.", created: D(-58) },
    { id: "ap-005", title: "MY-26-005 APU / Daniyal", lead: "l-004", university: "uni-010", course: "BSc (Hons) Computer Science", country: "MY", intake: "Jul-26", stage: "visa_filed", owner: "u-003", app_portal_ref: "EMGS-26/77120", tuition: 9500, currency: "MYR", offer_date: D(-34), cas_i20_date: D(-20), visa_filed_date: D(-11), priority: "Normal", agent: "ag-002", commission_pct: 15, notes: "eVAL issued. Sticker visa at High Commission — passport lodged since day of filing (11 days).", created: D(-70) },
    { id: "ap-006", title: "UK-26-006 UWL / Umair", lead: "l-006", university: "uni-003", course: "MSc Financial Technology", country: "UK", intake: "Jan-27", stage: "applied", owner: "u-003", application_fee: 0, tuition: 15600, currency: "GBP", priority: "High", notes: "Self-funded. Excellent candidate — push for Jan intake scholarship.", created: D(-8) },
    { id: "ap-007", title: "UK-26-007 Coventry / Noor", lead: "l-009", university: "uni-002", course: "International Foundation Year", country: "UK", intake: "Sep-26", stage: "approved", owner: "u-002", app_portal_ref: "CV-438871", tuition: 16420, currency: "GBP", offer_date: D(-95), cas_i20_date: D(-70), visa_filed_date: D(-52), visa_decision_date: D(-16), travel_date: D(21), priority: "Normal", agent: "ag-001", commission_pct: 20, notes: "VISA GRANTED. Flight + forex pending. Pre-departure briefing booked.", created: D(-140) },
    { id: "ap-008", title: "TR-26-008 YTU / Zoya", lead: "l-003", university: "uni-007", course: "BArch (Turkish, TÖMER)", country: "TR", intake: "Sep-26", stage: "new", owner: "u-002", tuition: 2400, currency: "USD", priority: "Low", notes: "Scholarship track only — will not pay private tuition.", created: D(0) },
  ],

  documents: [
    { id: "d-001", application: "ap-001", group: "Academic", item: "Transcripts + Degree", required: true, status: "Verified", date: D(-10), expiry: "", owner: "u-002", file_ref: "scan/areeba_transcripts.pdf" },
    { id: "d-002", application: "ap-001", group: "Academic", item: "IELTS UKVI (for SELT)", required: true, status: "Verified", date: D(-10), owner: "u-002", file_ref: "scan/areeba_ielts.pdf" },
    { id: "d-003", application: "ap-001", group: "Academic", item: "SOP / Personal Statement", required: true, status: "Pending", owner: "u-002", notes: "Draft v2 sent to student for edits" },
    { id: "d-004", application: "ap-001", group: "Financial", item: "Bank Statement (28 days, rolling)", required: true, status: "Overdue", due: D(-3), date: D(-34), owner: "u-002", notes: "Statement is 34 days old — MUST be re-issued before filing, else refusal" },
    { id: "d-005", application: "ap-001", group: "Financial", item: "Sponsor Letter + Source of Funds", required: true, status: "Collected", date: D(-2), owner: "u-002" },
    { id: "d-006", application: "ap-001", group: "Visa", item: "CAS from University", required: true, status: "Not Started", owner: "u-002", notes: "Blocked by SOP + financials" },
    { id: "d-007", application: "ap-001", group: "Visa", item: "TB Test Certificate (IOM Islamabad)", required: true, status: "Not Started", due: D(18), owner: "u-004" },
    { id: "d-008", application: "ap-004", group: "Academic", item: "YÖK Denklik (equivalency) application", required: true, status: "In Progress", due: D(-24), owner: "u-004", notes: "5th week. Ege bureau chasing daily." },
    { id: "d-009", application: "ap-004", group: "Visa", item: "ICAB / Embassy Recommendation Letter", required: true, status: "Verified", date: D(-6), owner: "u-002" },
    { id: "d-010", application: "ap-004", group: "Visa", item: "Residence Permit (IKAMET) appointment", required: true, status: "Not Started", due: D(120), owner: "u-004", notes: "Negative-deadline item: must be booked within 20 days AFTER arrival" },
    { id: "d-011", application: "ap-005", group: "Visa", item: "EMGS Student Pass Application (VAL)", required: true, status: "Verified", date: D(-22), owner: "u-004" },
    { id: "d-012", application: "ap-005", group: "Visa", item: "EMGS Medical Screening (FMT)", required: true, status: "Collected", date: D(-15), owner: "u-004" },
    { id: "d-013", application: "ap-007", group: "Visa", item: "Biometrics Appointment Confirmation", required: true, status: "Verified", date: D(-55), owner: "u-004" },
    { id: "d-014", application: "ap-007", group: "Financial", item: "Tuition Payment Receipt", required: true, status: "Verified", date: D(-80), owner: "u-005" },
    { id: "d-015", application: "ap-002", group: "Financial", item: "Proof of Funds €10,000+ living costs", required: true, status: "Rejected", date: D(-6), owner: "u-004", notes: "Short by €3,100 + no source explanation for recent PKR 4.5M credit" },
    { id: "d-016", application: "ap-003", group: "Visa", item: "CAS from University", required: true, status: "Not Started", due: D(12), owner: "u-002", notes: "Coventry issues CAS max 6 months before course start" },
  ],

  tasks: [
    { id: "t-001", title: "Re-issue 28-day bank statement for Areeba", application: "ap-001", lead: "l-001", due: D(-1), assignee: "u-002", type: "Document", status: "Open", priority: "Urgent", auto: false, notes: "Absolute rule — do not file with a 33-day-old statement." },
    { id: "t-002", title: "ATAS pre-check: does Greenwich MSc Data Science need it?", application: "ap-001", lead: "l-001", due: D(2), assignee: "u-002", type: "Other", status: "Doing", priority: "High", auto: false },
    { id: "t-003", title: "Call Hamza re: accumulation plan for €10k funds", application: "ap-002", lead: "l-002", due: D(-4), assignee: "u-003", type: "Call", status: "Open", priority: "High", auto: false, notes: "SLA BREACHED — 4 days late" },
    { id: "t-004", title: "Chase DBS admissions for conditional offer outcome", application: "ap-002", lead: "l-002", due: D(3), assignee: "u-003", type: "Follow-up", status: "Open", priority: "Normal", auto: true },
    { id: "t-005", title: "Draft CAS request email to Coventry (Mahnoor)", application: "ap-003", lead: "l-005", due: D(1), assignee: "u-002", type: "Drafting", status: "Open", priority: "High", auto: false },
    { id: "t-006", title: "Denklik escalation via Ege Education Bureau", application: "ap-004", lead: "l-007", due: D(0), assignee: "u-004", type: "Follow-up", status: "Doing", priority: "Urgent", auto: false },
    { id: "t-007", title: "Confirm EMGS eVAL sticker collection schedule", application: "ap-005", lead: "l-004", due: D(1), assignee: "u-004", type: "Document", status: "Open", priority: "High", auto: false },
    { id: "t-008", title: "Pre-departure briefing — Noor Fatima (travel in 3 weeks)", application: "ap-007", lead: "l-009", due: D(5), assignee: "u-002", type: "Meeting", status: "Open", priority: "Normal", auto: true },
    { id: "t-009", title: "Send forex + baggage allowance guide to Noor", application: "ap-007", lead: "l-009", due: D(7), assignee: "u-002", type: "Other", status: "Open", priority: "Low", auto: true },
    { id: "t-010", title: "Renew Gulf Star consultant agreement (expired)", assignee: "u-001", due: D(-25), type: "Other", status: "Open", priority: "High", auto: false, notes: "No signed agreement = do not release commission on MY-26-005." },
    { id: "t-011", title: "Collect Mahnoor visa-filing invoice balance", assignee: "u-005", due: D(4), type: "Fee", status: "Open", priority: "High", auto: true },
    { id: "t-012", title: "TÖMER C1 registration for Zoya (if no IELTS)", lead: "l-003", due: D(9), assignee: "u-002", type: "Other", status: "Open", priority: "Low", auto: false },
  ],

  activities: [
    { id: "a-001", when: D(-1), channel: "WhatsApp", direction: "Outbound", lead: "l-001", application: "ap-001", subject: "Sent SOP final edits + statement re-issue reminder", outcome: "Docs Committed", next_action_date: D(1), user: "u-002", body: "Mother confirmed new statement from Meezan on Monday." },
    { id: "a-002", when: D(-4), channel: "Call", direction: "Outbound", lead: "l-002", application: "ap-002", subject: "No answer x2 — funds discussion pending", outcome: "No Answer", user: "u-003", body: "Rang at 11am and 6pm. Try after 8pm." },
    { id: "a-003", when: D(-6), channel: "Meeting", direction: "Inbound", lead: "l-003", subject: "Walk-in counselling with father", outcome: "Reached", next_action_date: D(0), user: "u-002", body: "Budget capped at USD 4k/yr. Recommended Yildiz state + Turkiye Burslari as parallel application." },
    { id: "a-004", when: D(-8), channel: "Email", direction: "Outbound", lead: "l-006", application: "ap-006", subject: "UWL application submitted, portal creds shared", outcome: "Reached", user: "u-003", body: "Ref: portal login sent. 10-15 working days for decision." },
    { id: "a-005", when: D(-9), channel: "Email", direction: "Inbound", lead: "l-005", application: "ap-003", subject: "Coventry unconditional offer + £4k scholarship", outcome: "Reached", user: "u-002", body: "Deposit GBP 1,500 paid via bank transfer. CAS eligible from now." },
    { id: "a-006", when: D(-11), channel: "Call", direction: "Outbound", lead: "l-008", subject: "Advised passport renewal before Malaysia file", outcome: "Callback Set", next_action_date: D(-6), user: "u-003", body: "Family refused to renew — considering Feb-27 instead." },
    { id: "a-007", when: D(-12), channel: "WhatsApp", direction: "Inbound", lead: "l-009", application: "ap-007", subject: "Flight booking request + parent contact", outcome: "Reached", user: "u-002", body: "Travel 21 days out. Sent forex checklist." },
    { id: "a-008", when: D(-14), channel: "Call", direction: "Outbound", lead: "l-010", subject: "Final retention call — declined", outcome: "Not Interested", user: "u-003", body: "Already paid another consultancy GBP 250. Marked lost, revisit Sep-27." },
    { id: "a-009", when: D(-2), channel: "SMS", direction: "Outbound", lead: "l-004", application: "ap-005", subject: "Embassy passport collection alert", outcome: "Callback Set", next_action_date: D(1), user: "u-004", body: "High Commission will call for collection — inform student to keep EMGS letters ready." },
    { id: "a-010", when: D(-3), channel: "Meeting", direction: "Inbound", lead: "l-007", application: "ap-004", subject: "Original doc handover receipt signed", outcome: "Reached", user: "u-004", body: "Took originals against sign; return after visa decision." },
    { id: "a-011", when: D(-22), channel: "Email", direction: "Outbound", lead: "l-001", application: "ap-001", subject: "Sent ATAS guidance + university reply", outcome: "Reached", user: "u-002", body: "Greenwich says only a minority of projects require ATAS." },
    { id: "a-012", when: D(-16), channel: "WhatsApp", direction: "Inbound", lead: "l-005", application: "ap-003", subject: "Sponsor asked about 28-day rule", outcome: "Docs Committed", user: "u-002", body: "Explained rolling 28-day maintenance of funds with statement dated post-decision." },
  ],

  invoices: [
    { id: "i-001", number: "INV-26-101", lead: "l-001", application: "ap-001", issued: D(-20), due: D(-6), head: "Application Processing", amount: 25000, currency: "PKR", paid: 25000, status: "Paid", method: "Bank Transfer", notes: "Full processing fee, 50% at enrolment of file" },
    { id: "i-002", number: "INV-26-102", lead: "l-002", application: "ap-002", issued: D(-30), due: D(-16), head: "Counselling", amount: 5000, currency: "PKR", paid: 5000, status: "Paid", method: "Cash" },
    { id: "i-003", number: "INV-26-103", lead: "l-005", application: "ap-003", issued: D(-8), due: D(-1), head: "Visa Filing", amount: 35000, currency: "PKR", paid: 15000, status: "Partially Paid", method: "Online", notes: "Auto-raised at Offer stage. Balance 20,000 due." },
    { id: "i-004", number: "INV-26-104", lead: "l-007", application: "ap-004", issued: D(-40), due: D(-26), head: "Document Attestation", amount: 22000, currency: "PKR", paid: 0, status: "Overdue", method: "", notes: "26 days overdue — MOFA + notarisation advanced by us" },
    { id: "i-005", number: "INV-26-105", lead: "l-004", application: "ap-005", issued: D(-50), due: D(-36), head: "Visa Filing", amount: 40000, currency: "PKR", paid: 40000, status: "Paid", method: "Bank Transfer" },
    { id: "i-006", number: "INV-26-106", lead: "l-009", application: "ap-007", issued: D(-100), due: D(-86), head: "Application Processing", amount: 30000, currency: "PKR", paid: 30000, status: "Paid", method: "Cheque" },
    { id: "i-007", number: "INV-26-107", lead: "l-009", application: "ap-007", issued: D(-14), due: D(-1), head: "Pre-departure Briefing", amount: 15000, currency: "PKR", paid: 0, status: "Overdue", notes: "Send WhatsApp reminder template #PD-1" },
    { id: "i-008", number: "INV-26-108", lead: "l-006", application: "ap-006", issued: D(-5), due: D(9), head: "SOP/Essay Drafting", amount: 12000, currency: "PKR", paid: 0, status: "Sent", method: "" },
    { id: "i-009", number: "INV-26-109", lead: "l-008", issued: D(-25), due: D(-11), head: "Counselling", amount: 5000, currency: "PKR", paid: 0, status: "Waived", notes: "Waived — budget family, potential Malaysia Feb-27 + sibling" },
    { id: "i-010", number: "INV-26-110", lead: "l-010", issued: D(-70), due: D(-56), head: "Counselling", amount: 5000, currency: "PKR", paid: 5000, status: "Paid", method: "Cash" },
  ],

  templates: [
    { id: "tp-001", name: "First Response (WhatsApp)", channel: "WhatsApp", trigger: "Stage Change", subject: "", body: "Assalam-o-Alaikum {{student_name}}! This is {{counselor_name}} from {{brand}}. Thanks for your interest in {{country}} for {{intake}}. I've reviewed your profile — can we do a free 20-min counselling call tomorrow? We'll cover university shortlist, cost breakdown and visa success factors." },
    { id: "tp-002", name: "Doc Checklist Reminder", channel: "WhatsApp", trigger: "Doc Pending", subject: "Pending documents — {{app_title}}", body: "Dear {{student_name}}, the following are still PENDING for your {{country}} application:\n{{pending_docs}}\n⚠ Missing docs push your intake back — UK/Ireland strictly enforce the 28-day financial rule. Please share by {{due_date}}. Any questions, call me on {{counselor_phone}}." },
    { id: "tp-003", name: "28-Day Funds Rule (UK/IE)", channel: "WhatsApp", trigger: "Doc Pending", subject: "", body: "{{student_name}}, important UK/IE rule: your account must hold the required funds for 28 CONSECUTIVE days, and the statement must be dated within 31 days of application. Please do NOT spend from that account, don't add new deposits, and send me the fresh statement on day 29." },
    { id: "tp-004", name: "Fee Reminder", channel: "WhatsApp", trigger: "Fee Due", subject: "Invoice {{invoice_no}}", body: "Dear {{student_name}}, our records show {{head}} of PKR {{amount}} is due on {{due_date}} (invoice {{invoice_no}}). To avoid delays in filing with the university/embassy, please clear it via {{pay_channel}} and share a screenshot here. Thank you — {{brand}} Accounts." },
    { id: "tp-005", name: "Visa Kit Ready / CAS Instructions", channel: "Email", trigger: "Stage Change", subject: "{{country}} Visa — next steps & CAS instructions", body: "Dear {{student_name}},\n\nCongratulations — your {{university_name}} CAS/acceptance is issued. Next steps in order:\n1. Verify all CAS details within 6 months of use.\n2. Complete TB/medical test ({{medical_center}}) — book now, slots fill fast.\n3. Pay IHS/insurance and keep the reference number.\n4. Upload financials — 28-day rule applies.\n5. Biometrics: {{biometric_slot}}\n\nDocument list attached. Reply to this email with the completed set.\n\nRegards,\n{{counselor_name}}, {{brand}}" },
    { id: "tp-006", name: "Passport Lodged with Embassy", channel: "SMS", trigger: "Manual", subject: "", body: "{{student_name}}: your passport is with the {{country}} embassy (filed {{filed_date}}). Standard processing 15-30 working days. We update you every Friday. — {{brand}}" },
    { id: "tp-007", name: "Pre-departure Briefing Invite", channel: "WhatsApp", trigger: "Pre-departure", subject: "Pre-departure briefing", body: "{{student_name}}, your briefing is booked for {{briefing_date}} at {{branch}}. Bring: passport, CAS/eVAL originals, offer letter, forex receipts, accommodation contract. We'll cover airport pickup, SIMS, bank account in the UK, part-time work rules (20 hrs/week) and what to declare at customs." },
    { id: "tp-008", name: "Agent Commission Statement", channel: "Email", trigger: "Manual", subject: "Commission statement — {{period}}", body: "Dear {{partner_name}},\n\nConfirmed placements for the period:\n{{commission_rows}}\n\nTotal payable: PKR {{commission_total}}\nRelease policy: 100% after visa approval, subject to a signed current agreement (see expiry).\n\nRegards,\nAccounts, {{brand}}" },
    { id: "tp-009", name: "EMGS Timeline Update (Malaysia)", channel: "WhatsApp", trigger: "Stage Change", subject: "", body: "{{student_name}}, EMGS update for {{university_name}}: VAL status is {{emgs_status}}. Expected eVAL: {{eval_date}}. Please keep the MYR {{funds_amount}} untouched in the account — EMGS re-checks proof of funds at the eVAL stage too." },
    { id: "tp-010", name: "Residence Permit (Türkiye) Post-Arrival", channel: "WhatsApp", trigger: "Manual", subject: "", body: "{{student_name}} — welcome to Türkiye! ⚠ MANDATORY: apply for your Ikamet (residence permit) within 20 DAYS of arrival or you'll face a fine/exit ban. Appointment slots at the provincial migration office go fast — book online today and send me the confirmation." },
  ],

  contacts: [
    { id: "c-001", name: "Rukhsana Siddiqui", role: "Guardian", phone: "+92 336 2100112", email: "rukhsana.s@gmail.com", org: "Meezan Bank (Manager)", lead: "l-001", notes: "Areeba's mother. Financial sign-off person. Prefers calls after 6pm." },
    { id: "c-002", name: "Admissions Office — Postgraduate", role: "University Admissions", phone: "+44 20 8331 9520", email: "international@greenwich.ac.uk", org: "University of Greenwich", notes: "Reply SLA 3-5 working days. Mention our agent code AG-4471." },
    { id: "c-003", name: "Visa Officer (Student Route)", role: "Embassy", phone: "+92 21 3458 9000", email: "", org: "British Deputy High Commission Karachi", notes: "VFS only — no direct email. Escalate via ukvi@fco.gov.uk after 30 working days." },
    { id: "c-004", name: "Dr. Sameer Qadir", role: "Other", phone: "+92 311 2233445", email: "sameer@iomislamabad.org", org: "IOM — TB Testing", notes: "Book panel physician slot 4-6 weeks before application. Bring CAS." },
    { id: "c-005", name: "Ahmed Sheikh", role: "Guardian", phone: "+92 301 5566779", email: "", org: "Self-employed (textile)", lead: "l-002", notes: "Hamza's father. Explains the 4.5M PKR lump credit as property sale — needs deed." },
    { id: "c-006", name: "Accounts — Finance", role: "Bank", phone: "+92 21 111-637-637", email: "", org: "Meezan Bank", notes: "Statement with bank stamp + officer signature required for UK/IE." },
  ],
};

// Document status → progress weight
export const DOC_STATUS = ["Not Started", "Pending", "Collected", "In Progress", "Under Review", "Verified", "Rejected", "Overdue"];
export const DOC_DONE = new Set(["Verified", "Collected"]);
export const DOC_BLOCKED = new Set(["Rejected", "Overdue"]);
